CREATE DATABASE IF NOT EXISTS freeour DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
CREATE USER 'freeour'@'%' IDENTIFIED BY 'servicerequest';
GRANT ALL PRIVILEGES ON freeour.* TO 'freeour'@'%';
FLUSH PRIVILEGES;